query($id:ID!){
  recetas(filters:{autor:{id:{eq:$id}}}){
    data{
      id
      attributes{
        name
        categoria{
          data{
            id
            attributes{
              name
            }
          }
        }
      }
    }
  }
}